version: 2
jobs:
  build:
    docker:
      - image: base/devel
    working_directory: /data
    steps:
      - checkout
      - run:
          name: Copying file
          command: |
            mkdir -p out
            cat list.txt | xargs -I % cp % out
      - run:
          name: Packaging
          command: |
            cd out
            tar cvJf ../arch.tar.xz *
      - store_artifacts:
          path: /data/arch.tar.xz

workflows:
  version: 2
  build:
    jobs:
      - build